### ISSUE TITLE
Current implementation of the Datadog API is outdated and not valid

### ISSUE THREAD

**Issue by TMSCH** [coinbase/watchdog#12]
Hi,

I've setup Watchdog today and it looks like the APIs it relies on are invalid. Couple of issues I noticed:

- Monitors rely on an `/alert` endpoint, that does not exist anymore.
- Dashboard IDs are integer in Watchdog, but string in Datadog - so the configuration is broken.

Is there still active development on this project? It hasn't been updated in a while. Any fixes already available but not pushed to his open repo?

Thanks!
Thomas

**Comment by drewrothstein** [comment]
Hi,
We are archiving this repository and won't be submitting further patches.

Thank you!
